---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112600'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TeX-AutoTeX
no_index:
  directory:
    - t
    - inc
requires:
  CAM::PDF: 1.52
  Class::Accessor::Fast: 0.34
  Error: 0.17
  Test::More: 0
  arXiv::FileGuess: 0
  parent: 0.224
version: v0.906.0
